# In this exercise, an "infinite" generator is used to create a song about beverages. The lyrics are adjusted based on how many bottles of drink are left

def make_song(bottles = 99, drink = 'soda'):
        while True:
                if bottles > 1:
                        yield "{} bottles of {} on the wall.".format(bottles, drink)
                elif bottles > 0:
                        yield "Only 1 bottle of {} left!".format(drink)
                else:
                        yield "No more {}!".format(drink)
                        raise StopIteration
                bottles -= 1
        

soda_song = make_song()
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))
print(next(soda_song))





